#!/usr/bin/env python3
"""
Scrape Aquinas commentary on Pauline Epistles (and Job) from aquinas.cc API.
Uses the getCells endpoint which returns structured data.

Output format: BookAbbrev\tChapter:Verse\tAnnotation
"""

import requests
import re
import json
import time
import os

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EPISTLES_FILE = os.path.join(WORKSPACE, "aquinas-epistles.tsv")
JOB_FILE = os.path.join(WORKSPACE, "aquinas-job.tsv")

API_URL = "https://aquinas.cc/ws/Editor/getCells"
HEADERS = {"Content-Type": "application/json; charset=utf-8"}

# Pauline Epistles: (did, book_abbrev, display_name, total_rows)
EPISTLES = [
    (198, "Rom",  "Romans",           4199),
    (205, "1Cor", "1 Corinthians",    3856),
    (210, "2Cor", "2 Corinthians",    2141),
    (214, "Gal",  "Galatians",        1487),
    (218, "Eph",  "Ephesians",        1499),
    (222, "Phil", "Philippians",       686),
    (226, "Col",  "Colossians",        700),
    (230, "1Th",  "1 Thessalonians",   563),
    (234, "2Th",  "2 Thessalonians",   337),
    (238, "1Tim", "1 Timothy",        1016),
    (242, "2Tim", "2 Timothy",         664),
    (246, "Ti",   "Titus",             444),
    (250, "Phlm", "Philemon",          123),
    (255, "Heb",  "Hebrews",          3076),
]

# Job
JOB = [(177, "Job", "Job", 2590)]

# Fetch batch size
BATCH_SIZE = 500

def strip_html(text):
    """Remove HTML tags."""
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'&gt;', '>', text)
    text = re.sub(r'&lt;', '<', text)
    text = re.sub(r'&amp;', '&', text)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&#\d+;', '', text)
    return text.strip()

def fetch_all_rows(did, total_rows):
    """Fetch all rows for a text ID via the getCells API."""
    all_rows = []
    start = 0
    
    while start < total_rows:
        length = min(BATCH_SIZE, total_rows - start)
        payload = {"did": str(did), "start": start, "len": length}
        
        try:
            resp = requests.post(API_URL, headers=HEADERS, json=payload, timeout=30)
            if resp.status_code != 200:
                print(f"    HTTP {resp.status_code} at start={start}")
                break
            
            data = resp.json()
            if len(data) < 2:
                break
            
            rows = data[1]
            if not rows:
                break
            
            all_rows.extend(rows)
            start += length
            
            if start % 2000 == 0:
                print(f"    Fetched {start}/{total_rows} rows...")
            
            time.sleep(0.3)  # Polite delay
            
        except Exception as e:
            print(f"    Error at start={start}: {e}")
            time.sleep(2)
            start += length  # Skip problematic batch
    
    return all_rows

def parse_verse_ref(text):
    """
    Parse verse reference from text like "1:1 Paul, a servant..." 
    or "1:1 Paulus, servus..."
    Returns (chapter, verse_start, verse_end) or None.
    
    Also handles: "1:1-3 Text..." for ranges
    """
    text = strip_html(text).strip()
    
    # Pattern: "N:M Text..." or "N:M-P Text..."
    m = re.match(r'^(\d+):(\d+)(?:\s*[-–]\s*(\d+))?\s+(.+)?$', text)
    if m:
        ch = int(m.group(1))
        v_start = int(m.group(2))
        v_end = int(m.group(3)) if m.group(3) else v_start
        return (ch, v_start, v_end)
    
    # Pattern: just "N:M" with no trailing text (unlikely but possible)
    m = re.match(r'^(\d+):(\d+)(?:\s*[-–]\s*(\d+))?\.?\s*$', text)
    if m:
        ch = int(m.group(1))
        v_start = int(m.group(2))
        v_end = int(m.group(3)) if m.group(3) else v_start
        return (ch, v_start, v_end)
    
    return None

def is_structural_row(row_id):
    """
    In the aquinas.cc data, row IDs >= 4000 appear to be structural headers
    (chapter names, lecture names, section titles).
    Regular text rows have smaller IDs.
    """
    # Actually, let me check: in the Romans data, rows like 4206, 4187, 4120 were
    # structural. But row IDs below ~3000 seemed to be actual content.
    # A better heuristic: structural rows come BETWEEN the regular row sequences.
    # For now, we'll classify based on the text content.
    return False  # We'll use content-based classification

def is_gem(text):
    """Mark especially significant passages."""
    gem_phrases = [
        'god became man', 'word was made flesh', 'incarnation of the word',
        'mother of god', 'ever virgin', 'resurrection from the dead',
        'trinity', 'hypostatic', 'real presence', 'transubstantiation',
        'eternal generation', 'mystical body', 'regenerated by baptism',
        'primacy of peter', 'keys of the kingdom', 'infallibility',
        'justification by faith', 'justification by grace', 'free will',
        'predestination', 'beatific vision', 'the soul is immortal',
    ]
    tl = text.lower()
    for p in gem_phrases:
        if p in tl and len(text) > 400:
            return True
    return False

def process_rows(rows, book_abbrev):
    """
    Process raw API rows into (book_abbrev, ch:v, commentary) triples.
    
    Data structure:
    - Each row is [row_id, text_html]
    - Rows with high IDs (>=4000) are structural (chapter/lecture/section titles)
    - Rows with verse refs like "1:1 Paul..." identify the verse being commented on
    - Commentary rows follow the verse ref rows
    """
    results = []
    
    current_ch_v = None   # (chapter, verse_start, verse_end)
    current_comment = []  # List of text strings
    
    def flush():
        if current_ch_v and current_comment:
            ch, v_start, v_end = current_ch_v
            text = ' '.join(current_comment).strip()
            text = clean_text(text)
            if len(text) > 30:
                if is_gem(text):
                    text += ' # GEM'
                for v in range(v_start, v_end + 1):
                    results.append((book_abbrev, f"{ch}:{v}", text))
    
    for (row_id, raw_text) in rows:
        text = strip_html(raw_text)
        
        # Skip empty
        if not text or len(text) < 2:
            continue
        
        # Skip structural headers (chapter/lecture titles like "Chapter 1", "Lecture 1")
        # These tend to be short titles
        if re.match(r'^Chapter\s+\d+$', text) or re.match(r'^Lecture\s+\d+$', text):
            continue
        if re.match(r'^Commentary on\s+', text) or re.match(r'^Prologue$', text, re.I):
            continue
        
        # Check if this is a verse reference row
        verse_ref = parse_verse_ref(text)
        if verse_ref:
            # Flush previous verse
            flush()
            current_ch_v = verse_ref
            current_comment = []
            # Some verse ref rows have the verse text as trailing content
            # We don't need the verse text itself, just the reference
            continue
        
        # If we have a current verse, accumulate this as commentary
        if current_ch_v is not None:
            # Skip footnote-only lines and very short lines
            if len(text) > 5:
                current_comment.append(text)
    
    # Final flush
    flush()
    
    return results

def clean_text(text):
    """Clean commentary text for TSV."""
    # Remove tab characters
    text = text.replace('\t', ' ')
    # Normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()
    # Remove paragraph numbers at start like "15." or "15. 16."
    # These are fine to keep actually - helps reader find sections
    return text

def write_tsv_header(filepath):
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write("Book\tVerse\tCommentary\n")

def append_tsv_rows(filepath, rows):
    with open(filepath, 'a', encoding='utf-8') as f:
        for (book, ref, ann) in rows:
            ann_clean = ann.replace('\n', ' ')
            f.write(f"{book}\t{ref}\t{ann_clean}\n")

def process_book(did, book_abbrev, display_name, total_rows):
    """Fetch and process a full book."""
    print(f"\n=== {display_name} (did={did}, ~{total_rows} rows) ===")
    
    raw_rows = fetch_all_rows(did, total_rows)
    print(f"  Fetched {len(raw_rows)} rows total")
    
    results = process_rows(raw_rows, book_abbrev)
    print(f"  Parsed {len(results)} verse entries")
    
    return results

def main():
    print("=== Aquinas Epistles Scraper (aquinas.cc API) ===")
    
    # Initialize output files
    write_tsv_header(EPISTLES_FILE)
    write_tsv_header(JOB_FILE)
    
    # Process Pauline Epistles
    print("\n### PAULINE EPISTLES ###")
    epistles_total = 0
    
    for (did, abbrev, name, rows) in EPISTLES:
        book_rows = process_book(did, abbrev, name, rows)
        if book_rows:
            append_tsv_rows(EPISTLES_FILE, book_rows)
            epistles_total += len(book_rows)
            print(f"  Written {len(book_rows)} rows for {name}")
    
    print(f"\nEpistles total: {epistles_total} verse entries → {EPISTLES_FILE}")
    
    # Process Job
    print("\n### JOB ###")
    job_total = 0
    
    for (did, abbrev, name, rows) in JOB:
        book_rows = process_book(did, abbrev, name, rows)
        if book_rows:
            append_tsv_rows(JOB_FILE, book_rows)
            job_total += len(book_rows)
            print(f"  Written {len(book_rows)} rows for {name}")
    
    print(f"\nJob total: {job_total} verse entries → {JOB_FILE}")
    
    print(f"\n=== COMPLETE ===")
    print(f"Epistles: {epistles_total} verse entries")
    print(f"Job: {job_total} verse entries")

if __name__ == '__main__':
    main()
